### ISSUE TITLE
Require multiple conditions

### ISSUE THREAD

**Issue by jdarwood007** [jdarwood007/StopForumSpam#9]
We should have a require selections.

Would be like this:
- Any (IP/Email/Name) [Current/Default action]
- Email & IP
- Email & Username
- Username & IP

**Comment by EL34xyz** [comment]
Hi,
On my forum, I get assaulted by known spammers every day
This morning, there were 10 attempts to register that all had two or more spam data base hits

I would like to be able to set my registration parameters to not allow registering if the **IP AND Email** are in the spam data base.
There's no reason I would ever allow any of these attempts to become forum members

On my web site, I send IP's that are trying to abuse PHP scripts to a 404 page.
The attempts from that IP stop after that

User name is not important to me because the Name BOB is in the spam database, but if that user name is not taken, I would allow BOB to join the forum if his IP and Email were not in the spam data base.

My registration rule would be something like this
If the **IP and Email** are in the spam database, send the spammer to some other page
Maybe even report them so that the username gets tagged also in case that was not in the spam data base

Look at the screen shot from this mornings registration attempts

**Comment by EL34xyz** [comment]
Forgot the screen shot

![ForumSpammers](https://user-images.githubusercontent.com/16766383/210842872-30caf7e4-ae33-4973-8cbf-c04dff704deb.png)

**Comment by EL34xyz** [comment]
And here is the next mornings attempted registrations

![ForumSpammers2](https://user-images.githubusercontent.com/16766383/211046564-53028eeb-342a-4c34-bc11-583775f05506.png)
